export { default as Home } from "./Home/index";
export { default as Login } from "./Login/index";
export { default as Admin } from "./Admin/index";
export { default as Profile } from "./Profile/index";
export { default as Share } from "./Share/index";
export { default as resetPassword } from "./PasswordReset/index";
export { default as ScannedResult } from "./ScanResult/index";
export { default as Register } from "./Register/index";
export { default as ContactUs } from "./ContactUs/index";
